export const apiEndpoints = {
  login: "/api/v1/auth/login",
  adminProducts: "/api/v1/admin/products",
  adminProduct: (id: string) => `/api/v1/admin/products/${id}`,
  adminProductPublish: (id: string) => `/api/v1/admin/products/${id}/publish`,
  adminProductImage: (id: string) => `/api/v1/admin/products/${id}/images`,
  adminProductVariant: (id: string) => `/api/v1/admin/products/${id}/variants`,
  adminUpload: "/api/v1/admin/media/upload",
  adminMedia: "/api/v1/admin/media",
  adminMediaItem: (filename: string) => `/api/v1/admin/media/${filename}`,
  adminBrands: "/api/v1/admin/brands",
  adminCategories: "/api/v1/admin/categories",
  adminCategory: (id: number) => `/api/v1/admin/categories/${id}` ,
  adminAttributes: "/api/v1/admin/attributes",
  adminQuotes: "/api/v1/admin/quotes",
  adminDataQuality: "/api/v1/admin/data-quality",
  adminIntelligenceSummary: "/api/v1/admin/intelligence/summary",
  adminAnalytics: "/api/v1/admin/analytics",
  adminIntelligenceDataQuality: "/api/v1/admin/intelligence/data-quality",
  adminIntelligenceSyncHealth: "/api/v1/admin/intelligence/sync-health",
  adminIntelligenceOverrideConflicts: "/api/v1/admin/intelligence/override-conflicts",
  adminSyncTrigger: "/api/v1/admin/sync/pim",
  adminSyncRuns: "/api/v1/admin/sync/runs",
  adminPimSources: "/api/v1/admin/pim/sources",
  adminPimSourceTest: (id: number) => `/api/v1/admin/pim/sources/${id}/test`,
  adminPimRunImport: "/api/v1/admin/pim/run-import",
  adminPimImports: "/api/v1/admin/pim/imports",
  adminPimDataQuality: "/api/v1/admin/pim/data-quality",
  adminHejcoIntegration: "/api/v1/admin/integrations/hejco",
  adminHejcoIntegrationTest: "/api/v1/admin/integrations/hejco/test",
  adminHejcoIntegrationSync: "/api/v1/admin/integrations/hejco/sync",
  adminSupplierSync: "/api/v1/admin/integrations/sync",
  adminContent: "/api/v1/admin/content",
  quotes: "/api/v1/quotes",
  publicProducts: "/api/v1/products",
  publicCategories: "/api/v1/categories",
  publicFilters: "/api/v1/filters",
  publicSearch: "/api/v1/search",
  publicSearchSuggestions: "/api/v1/search/suggestions",
  publicProduct: (slug: string) => `/api/v1/products/${slug}`,
  publicProductSearch: "/api/v1/products/search"
} as const;
